<?php

return [
    'performances' => [
        'Visita di medicina generale',
        'Visita ginecologica',
        'Visita urologica',
        'Visita oculistica',
        'Visita otorinolaringoiatrica',
        'Visita cardiologica',
        'Visita gastroenterologica',
        'Visita endocrinologica',
        'Visita neurologica',
        'Visita psichiatrica',
        'Visita allergologica',
        'Visita dermatologica',
        'Visita diabetologica',
        'Visita endocrinologica',
        'Visita ginecologica',
        'Visita immunologica',
        'Visita infettivologica',
        'Visita nefrologica',
        'Visita nutrizionale',
        'Visita oncologica',
        'Visita ortopedica',
        'Visita otorinolaringoiatrica',
        'Visita pediatrica',
        'Visita pneumologica',
        'Visita reumatologica',
        'Visita urologica',
        'Visita medica preassuntiva',
        'Visita medica periodica',
        'Visita medica su richiesta',
        'Visita medica per cambio di mansione',
        'Visita medica per infortunio',
        'Visita medica per cessazione del rapporto',
        'Visita per la certificazione di idoneità sportiva',
        "Visita per la certificazione di idoneità per il porto d'armi",
        'Visita per la certificazione di idoneità per il patentino di guida',
        'Visita per la certificazione di idoneità per la scuola',
    ],
];
